name: CI/CD

#env:
#  EB_PACKAGE_S3_BUCKET_NAME : "demo-bucket-cicd"
#  DEPLOY_PACKAGE_NAME       : "flask-app-${{ github.sha }}.jar"
#  AWS_REGION_NAME           : "us-east-1"
  

on:
  push:
    branches: [master]

jobs:
  
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Use java ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         java-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: npm install
      - run: npx create-nx-workspace@latest
      - name: Run Affected Tests
        shell: bash
        run: npm run affected:test -- --base=remotes/origin/master
#      - name: Build, Test and Publish package (.jar file) to GitHub
#        run: mvn -B clean package

#      - name: Configure my AWS Credentils
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#             aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
#             aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
#             aws-region           : ${{ env.AWS_REGION_NAME }}

#      - name: Copy our Deployment package to S3 bucket
#        run : aws s3 cp /home/runner/work/petclinic-classic-ci-cd-aws/petclinic-classic-ci-cd-aws/target/petclinic.war s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/

#      - name: Print nice message on completion of CI Pipeline
#        run : echo "CI Pipeline part finished successfully"
          
     
